name: Daily Quote Commit

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # important!

      - name: Set Git user
        run: |
          git config user.name "Ravi-vira"
          git config user.email "vira5642@gmail.com"

      - name: Fetch quote and update file
        run: |
          quote=$(curl -s https://api.quotable.io/random | jq -r '.content + " — " + .author')
          echo "$(date): $quote" >> quotes.txt

      - name: Commit and push
        run: |
          git add quotes.txt
          git commit -m "📜 Added quote for $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
